# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'timecoco' do

pod 'AsyncDisplayKit'
pod 'DHSmartScreenshot'
pod 'FMDB'
pod 'REFrostedViewController'
pod 'SVProgressHUD'
pod 'TTTAttributedLabel'

end

target 'timecocoTests' do

end

target 'extension' do

end

