source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'AsyncDisplayKit'
pod 'DHSmartScreenshot'
pod 'FMDB'
pod 'REFrostedViewController'
pod 'SVProgressHUD'
pod 'TTTAttributedLabel'